/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luck
 */
public class Reparacion extends javax.swing.JFrame {

    String user,rol,Cant;
    int cantpro,filasele=0;
    Connection miConexion;
    String data[][]={};
    String cabecera[]={"Numero","Tipo de Movimiento","Fecha","Cantidad","Producto","Usuario","Provedor"};
    DefaultTableModel table;
    Screensize pantalla = new Screensize();
    Mysqlconector conexion = new Mysqlconector();
    public Reparacion(String usuario,String role){
        user= usuario;
        rol=role;
        initComponents();
        this.getContentPane().setBackground(Color.lightGray);
        table= new DefaultTableModel(data,cabecera);
        this.tabla.setModel(table);
        //tabla.removeColumn(tabla.getColumnModel().getColumn(0));
        Actualizar();
        this.cantidad.setEnabled(false);
    }
    private void Actualizar(){
        try {
            miConexion = conexion.Connection().getConnection();
            String query ="SELECT * FROM query_movimiento WHERE tipo_mov='Reparacion' AND status=1 GROUP BY id_mov";         
            // create the java statement
            Statement st = miConexion.createStatement();
            ResultSet rs = st.executeQuery(query);
            //checamos que haya usuarios correctos 
            cantpro=0;
            while(rs.next()){
               
                String datos[]={rs.getString("id_mov"),rs.getString("tipo_mov"),rs.getString("fecha_mov"),rs.getString("cantidad_mov"),rs.getString("producto"),rs.getString("usuario"),rs.getString("provedor")};
                table.addRow(datos);
                cantpro+=Integer.parseInt(rs.getString("cantidad_mov"));
            }
           this.cantidad.setText(Integer.toString(cantpro));
        } catch (SQLException ex) {
            Logger.getLogger(Reparacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog = new javax.swing.JDialog();
        file = new javax.swing.JTextField();
        seleccionar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        cantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        exp = new javax.swing.JButton();
        busqueda = new javax.swing.JTextField();
        busqu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        date2 = new com.toedter.calendar.JDateChooser();
        reparado = new javax.swing.JButton();

        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });

        seleccionar.setText("Seleccionar archivo");
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });

        guardar.setText("Save");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogLayout = new javax.swing.GroupLayout(jDialog.getContentPane());
        jDialog.getContentPane().setLayout(jDialogLayout);
        jDialogLayout.setHorizontalGroup(
            jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLayout.createSequentialGroup()
                .addGroup(jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(file, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(seleccionar))
                    .addGroup(jDialogLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jDialogLayout.setVerticalGroup(
            jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLayout.createSequentialGroup()
                .addGroup(jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(seleccionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 111, -1));

        jLabel1.setText("Cantidad en reparacion: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 28));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 177, 802, 298));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 12, 139, 25));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresa_01.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 514, 78, 45));

        exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.gif"))); // NOI18N
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });
        getContentPane().add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 514, 204, 45));
        getContentPane().add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 85, 173, -1));

        busqu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.jpeg"))); // NOI18N
        busqu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquActionPerformed(evt);
            }
        });
        getContentPane().add(busqu, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 85, 75, 47));

        jLabel3.setText("Multibusqueda");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 85, -1, 28));

        jLabel4.setText("Fecha inicial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 37, -1, 28));

        date1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                date1KeyTyped(evt);
            }
        });
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 37, 163, -1));

        jLabel5.setText("Fecha final");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 37, -1, 28));

        date2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                date2KeyTyped(evt);
            }
        });
        getContentPane().add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 37, 160, -1));

        reparado.setText("Reparado");
        reparado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reparadoActionPerformed(evt);
            }
        });
        getContentPane().add(reparado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Administrador a = new Administrador(user,rol);
         a.setVisible(true);
         a.setBounds((pantalla.ancho / 2) - (a.getWidth() / 2), (pantalla.alto / 2) - (a.getHeight() / 2), a.getWidth(),a.getHeight());
         this.dispose();
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed
    public void LimpiarJTable(){
        int a =table.getRowCount()-1;  //Índices van de 0 a n-1
        //System.out.println("Tabla "+a);   //Para mostrar por consola el resultado
        for(int i=a;i>=0;i--){ 

            //System.out.println("i "+i);    //Para mostrar por consola el resultado
            table.removeRow(i);
        }
    }
    public void llama_excel()
	 {
		 try {
				Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+file.getText()+".xls");
				} catch (IOException e) {
				// TODO Auto-generated catch block
                                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, e);
				}
	 }
    
    private void llamarJDialogExcel() {

        //Centramos nuestro jDialog
        jDialog.setLocationRelativeTo(this);
        //La hacemos modal
        jDialog.setModal(true);
        //Establecemos dimensiones.
        jDialog.setMinimumSize(new Dimension(500, 160));
        //Establecemos un título para el jDialog
        jDialog.setTitle("Imprimir en Excel");
        //La hacemos visible.
        jDialog.setVisible(true);
    }
    
    private void busquActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquActionPerformed
                    try {                                      
                        // TODO add your handling code here:
                        String query;
                        int band=0;
                         miConexion = conexion.Connection().getConnection();
                        query= "SELECT * FROM query_movimiento WHERE tipo_mov='Reparacion' AND status=1 AND ";
                        
                        if(date1.getCalendar()!=null && date2.getCalendar()==null || date2.getCalendar()!=null && date1.getCalendar()==null ){
                            JOptionPane.showMessageDialog(null, "Ingresar datos de fecha incial y final ","Error Busqueda",JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                     
                        if(date1.getCalendar()!=null && date2.getCalendar()!=null){
                            //validacion fechas
                            if(date2.getDate().before(date1.getDate())){
                                JOptionPane.showMessageDialog(null, "Fecha 1 debe ser menor que Fecha 2","Error Busqueda",JOptionPane.ERROR_MESSAGE);
                                return;
                            }
                            Date fecha = this.date1.getDate();
                            SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                            String fechaformato=formato.format(fecha);
                            String fechainicial=fechaformato.replaceAll("/", "-");
                            
                            Date fecha2 = this.date2.getDate();
                            SimpleDateFormat formato2 = new SimpleDateFormat("yyyy/MM/dd");
                            String fechaformato2=formato2.format(fecha2);
                            String fechafinal=fechaformato2.replaceAll("/", "-");
                            query +="fecha_mov >='"+fechainicial+"' AND fecha_mov <= '"+fechafinal+"' ";
                            band=1;
                            
                        }
                        if(!busqueda.getText().equals("")){
                            if(band==1)
                                query += "AND ";
                            
                            query +="(producto LIKE '%"+busqueda.getText()+"%' OR provedor LIKE '%"+busqueda.getText()+"%'\n" +
                                    "OR usuario LIKE '%"+busqueda.getText()+"%' OR tipo_mov = '"+busqueda.getText()+"') ";
                        }
                        if(date1.getCalendar()==null && date2.getCalendar()==null && busqueda.getText().equals("")){
                            query = "SELECT * FROM query_movimiento WHERE tipo_mov='Reparacion' AND status=1 ";
                        }
                        
                            //Limpiar tabla
                            LimpiarJTable();
                            query += "GROUP BY id_mov";
                            Statement st = miConexion.createStatement();
                            ResultSet rs = st.executeQuery(query);
                            while(rs.next()){       
                                //ingresar los nuevos datos a la tabla
                                String datos[]={rs.getString("id_mov"),rs.getString("tipo_mov"),rs.getString("fecha_mov"),rs.getString("cantidad_mov"),rs.getString("producto"),rs.getString("usuario"),rs.getString("provedor")};
                                table.addRow(datos);
                            }
                                                                     
                    } catch (SQLException ex) {
                        Logger.getLogger(Reparacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    finally{
                        Mysqlconector.liberaConexion(miConexion);
                    }
    }//GEN-LAST:event_busquActionPerformed

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        String cadena=this.cantidad.getText();    
          if(cadena.length()>9) {
             
              evt.consume();
              
              JOptionPane.showMessageDialog(null,"Longitu maxima de 10 digitos","Error Validacion",JOptionPane.ERROR_MESSAGE);
              
          }
          if(Character.isLetter(c))
            {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error Validacion",JOptionPane.ERROR_MESSAGE);
                cantidad.setCursor(null);
            }
            else if(c>32 &&c<=47||c>=58 && c<=64|| c>=91 && c<=96||c>=123 && c<=255)
           {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error Validacion",JOptionPane.ERROR_MESSAGE);
                cantidad.setCursor(null);
            }
         
        
    }//GEN-LAST:event_cantidadKeyTyped

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        // TODO add your handling code here:
          llamarJDialogExcel();
    }//GEN-LAST:event_expActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        try {      	 
           List<JTable> tb = new ArrayList<>();
           tb.add(tabla);
           //-------------------
           ExportaExcel excelExporter = new ExportaExcel(tb, new File(file.getText()+".xls"));
           if (excelExporter.export()) {
               JOptionPane.showMessageDialog(null, "DATOS EXPORTADOS CON EXITOS!");
           }
       } catch (Exception ex) {
              Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       }
         llama_excel();
         jDialog.dispose();
    }//GEN-LAST:event_guardarActionPerformed

    private void date1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date1KeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_date1KeyTyped

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        // TODO add your handling code here:
         JFileChooser dialog = new JFileChooser();
        int opcion = dialog.showSaveDialog(this);

        if(opcion == JFileChooser.APPROVE_OPTION){

            File dir = dialog.getSelectedFile();
            String fl = dir.toString();

            this.file.setText(fl);
        }
    }//GEN-LAST:event_seleccionarActionPerformed

    private void date2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date2KeyTyped
        
    }//GEN-LAST:event_date2KeyTyped

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
         filasele=tabla.getSelectedRow();
         this.cantidad.setText(tabla.getValueAt(filasele, 3).toString());
         
        // miConexion
    }//GEN-LAST:event_tablaMouseClicked

    private void reparadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reparadoActionPerformed
                   // TODO add your handling code here:
       int cantfila = table.getRowCount();
       int fila = tabla.getSelectedRow();
       if(cantfila==0){
         JOptionPane.showMessageDialog(null,"No hay Mobiliario en repracion","Error reparacion",JOptionPane.ERROR_MESSAGE);
         return;  
       }
      
       if(fila==-1){
         JOptionPane.showMessageDialog(null, "Seleccionar Registro de Mobiliario a Reparar","Error reparacion",JOptionPane.ERROR_MESSAGE);
         return;
       }
       try {  
            int id;         
            miConexion = conexion.Connection().getConnection();
            id = Integer.parseInt(tabla.getValueAt(fila, 0).toString());
            //cambiamos el estatus como reparado o funcional y regresamos existencia a nuestro producto
            // de que ya regreso el mobiliario que estaba en reparacion
            String queryupdate = "UPDATE Movimientos SET status=0 WHERE id_mov='"+id+"' ";
            Statement st = miConexion.createStatement();
            int cant = st.executeUpdate(queryupdate);
            if(cant >0){
                JOptionPane.showMessageDialog(null, "Se Regreso Mobiliario Reparado correctamente!");
                LimpiarJTable();
                Actualizar();
            }else
                JOptionPane.showMessageDialog(null, "Error al devolver Mobiliario reparado Intentelo de nuevo!","Error Reparacion",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Reparacion.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            Mysqlconector.liberaConexion(miConexion);
        }
    }//GEN-LAST:event_reparadoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
             //   new Reparacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busqu;
    private javax.swing.JTextField busqueda;
    private javax.swing.JTextField cantidad;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton exp;
    private javax.swing.JTextField file;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reparado;
    private javax.swing.JButton seleccionar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
